### ISSUE TITLE
files without matches again

### ISSUE THREAD

**Issue by otavioschwanck** [fdschmidt93/telescope-egrepify.nvim#15]
![image](https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/9551316/779cf92d-fe03-4d89-84c5-5c0db5cddb6a)

i managed to record:

At first, showing the bugged picker, returning a lot of files.
i closed and opened again, the bug disappears.

![bug](https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/9551316/e13db500-f06b-41b7-b0ff-138690bcf989)

Continuation of https://github.com/fdschmidt93/telescope-egrepify.nvim/issues/11

It is super rare to happen, but happen sometimes

**Comment by fdschmidt93** [comment]
When reporting an issue, please 

- provide a minimal config with system details and Neovim version
- exact reproduction steps

or otherwise I won't help you. Please understand it is not my burden to scavenger hunt details on your issue.

I'm somewhat puzzled why you keep ignoring repeated instructions of doing so and we have to start over. I was so far very supportive, and still it appears that you keep treating Github issues as shoving problems into a customer support line.

Kindly understand that, going forward, I will be simply closing issues that do not include both of the above.
