### ISSUE TITLE
Improve grep fuzzy_refine

### ISSUE THREAD

**Issue by otavioschwanck** [fdschmidt93/telescope-egrepify.nvim#17]
**Is your feature request related to a problem? Please describe.**
On `:Telescope livre_grep`, after hitting <C-space> you can search on the search results.  On egrepify it is possible too.  The difference is, when used on the egrepify, it only shows a lot of file title, without any matches.

`Telescope live_grep`:
![telescope live_grep](https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/9551316/b94638a7-99e9-4b1c-b139-3463e7ed3cf6)

On `Telescope egrepify` with the same search:
![telescope egrepify](https://github.com/fdschmidt93/telescope-egrepify.nvim/assets/9551316/7f0cf78a-866e-4ebe-838b-2da94b31496e)

On egrepify, i can select the title, but not the content.  The ideal here is:  if the match is on title, show the matches too (but i think its too hard to implement).

Another solution could be just switch to live_grep when hitting ctrl+space (to not mess with the stuff)

If there is another way to search on the results, after i typed what i wanted, i am open to test it.

I use a lot this C-space, the projects that i work are massive.

obs:
i could help to implement, but the plugin is too complex, if you want to me to take a look, send me where to look / change.

**Comment by fdschmidt93** [comment]
> On egrepify, i can select the title, but not the content. The ideal here is: if the match is on title, show the matches too (but i think its too hard to implement).

I don't fully follow what you are saying. But hovering the title and then showing other results is definitely out of the question.

The title should probably be filtered on fuzzy refine. We should just implement that. Right now, clicking on title just opens the file, but that doesn't make sense.

The primary complexity comes from the fact that the entry maker should change, since the title is not inlined any longer vis-a-vis `telescope.live_grep`.
