### ISSUE TITLE
LOVE this extension, question about grep_string

### ISSUE THREAD

**Issue by megalithic** [fdschmidt93/telescope-egrepify.nvim#9]
Is it possible to use this for `grep_string` instances/uses, not just for `live_grep`?

**Comment by fdschmidt93** [comment]
Glad you like it!

I'm not sure I 100% follow. What from `egrepify` would you want for `grep_string`? I assume you refer to how results are presented. However, that does not work as `rg` groups matches by file which `fzf-native` does not do.

Plus, `egrepify` is practically the reason why I do not use `grep_string`.

Closing this as unplanned since I do not see an actionable item here.

**Comment by megalithic** [comment]
@fdschmidt93

That is TOTALLY fair and understandable.

You're right, I didn't put _any_ context around that at all.

You nailed it though, wanting the formatting of results and the filtering for moments where you might grep for visually selected text. I didn't see it in the docs, is there a way to start live_grep off with a starting string?

**Comment by fdschmidt93** [comment]
Any telescope picker takes a `default_text` argument with which a search string can be initialized.

Here's how I do it in my dotfiles for visual selection: https://github.com/fdschmidt93/dotfiles/blob/c4c2dc208e84164e50bece2d033e62468a20eb6f/nvim/.config/nvim/lua/fds/mappings.lua#L55-L71

**Comment by megalithic** [comment]
Thanks for your time, and for the code examples.
